.PHONY: up down logs ps build seed seed-gen psql test test-docker test-frontend frontend-dev portal-dev config status eval

# Scoped gateway->ai-assistant secret file. Compose refuses to parse when a
# listed env_file is missing, so every compose target depends on this. The
# template ships the secret EMPTY on purpose: AI calls fail closed (503) until
# a real value is generated (see .env.ai-proxy.example).
.env.ai-proxy:
	cp .env.ai-proxy.example .env.ai-proxy

# Redis auth (docs/debt-log.md D3b), scoped to redis + gateway like the file
# above and listed as an env_file, so every compose target depends on it too.
# Unlike .env.ai-proxy this one is GENERATED rather than copied: an empty
# password makes the redis container refuse to start (fail-closed), and a
# template value would be a credential every checkout shares. One random
# password per machine, never committed.
.env.redis:
	@pw="$$(openssl rand -hex 32)"; \
	 [ -n "$$pw" ] || { echo "openssl rand failed — refusing to write an empty REDIS_PASSWORD" >&2; exit 1; }; \
	 printf '# Generated by `make` — scoped to redis + gateway (docs/debt-log.md D3b).\n# Rotate: delete this file, `make down && make up`; existing sessions are dropped.\nREDIS_PASSWORD=%s\n' "$$pw" > $@
	@echo "generated .env.redis with a random REDIS_PASSWORD"

up: .env.ai-proxy .env.redis   ## start the whole stack
	docker compose up -d

down: .env.ai-proxy .env.redis ## stop the stack
	docker compose down

logs: .env.ai-proxy .env.redis ## tail logs
	docker compose logs -f

ps: .env.ai-proxy .env.redis   ## service status
	docker compose ps

build: .env.ai-proxy .env.redis ## build all images
	docker compose build

seed: .env.ai-proxy .env.redis ## load schema + demo data (re-runs against a running db)
	docker compose exec -T postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend} < db/schema.sql
	docker compose exec -T postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend} < db/seed/seed.sql

# Written through a temp file, not redirected onto the target: since the
# generator started reading the fixture CSVs it has failure paths (missing
# file, changed row order), and a plain `> db/seed/seed.sql` truncates the
# target BEFORE the generator runs — leaving an empty seed.sql, which
# docker-compose.yml mounts into a fresh volume's initdb without complaint.
seed-gen:      ## regenerate db/seed/seed.sql from the generator (deterministic)
	python3 db/seed/generate_seed.py > db/seed/seed.sql.tmp \
	  && mv db/seed/seed.sql.tmp db/seed/seed.sql \
	  || (rm -f db/seed/seed.sql.tmp; false)

# eval/rag/REPORT.md is a committed deliverable derived from db/seed/patients.csv,
# encounters.csv and goldset.json, and nothing noticed when the seed moved and the
# report went stale (tests/test_rag_eval.py asserts substrings, not bytes). This
# regenerates with the STUB retriever — torch-free and stdlib-only, so it runs under
# the system Python (3.8) like seed-gen and status, needs no container, no database
# and no network — and diffs against the committed file.
#
# §4's model-dependent cells are masked out of the diff: the committed report is
# embed-path output and its scores are not reproducible without the model. What is
# masked, what is deliberately NOT (the retriever label, each row's goldset-derived
# cells), and the blind spots that remain are owned by the header of
# eval/rag/check_drift.py — do not restate them here (§10.1). The mask and its red
# paths are pinned by tests/test_drift_check.py.
eval:          ## check eval/rag/REPORT.md + db/seed/seed.sql are current against their sources
	python3 eval/rag/check_drift.py

psql: .env.ai-proxy .env.redis ## open a psql shell
	docker compose exec postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend}

test:          ## run unit tests (no infra needed)
	pip install -r requirements-dev.txt >/dev/null
	pytest -m "not integration" -q

# Same suite as `test`, but in the 3.12 container CI uses — the only way to run it
# on a machine whose local Python is 3.8. The build is a no-op (~0.6s) unless
# requirements-dev.txt changed. Pass extra pytest args via ARGS, e.g.
#   make test-docker ARGS="tests/test_redaction.py -q"
test-docker:   ## run unit tests in the python:3.12 container (mirrors CI)
	docker build -q -t riverbend-test:py312 -f Dockerfile.test . >/dev/null
	docker run --rm -v "$$PWD":/repo -w /repo riverbend-test:py312 \
	  pytest $(if $(ARGS),$(ARGS),-m "not integration" -q)

# The JS gate, invocable the way the Python one is (ADR 0013 §5). It is a
# convenience over the same commands the CI `portal` job runs, NOT a second
# definition of the gate: this machine's Node is not the Node that deploys
# (CI and the runtime image both pin 22), so a green run here is evidence and
# CI is the proof. Needs `npx playwright install chromium` once for the
# browser project.
test-frontend: ## run the portal's JS gate (svelte-check, eslint, vitest)
	cd portal && npm ci && npm run check && npm run lint && npm test

frontend-dev:  ## run the legacy Next.js dev server (port 3070)
	cd frontend && npm install && npm run dev

portal-dev:    ## run the SvelteKit portal dev server (port 3071)
	cd portal && npm install && npm run dev -- --port 3071

config: .env.ai-proxy .env.redis ## validate the compose file
	docker compose config -q && echo "compose OK"

# Derives docs/status/dashboard.html from docs/specs/frontend-rebuild.md,
# docs/status/fe-verdicts.md, docs/todo.md and docs/debt-log.md. Reads only; stdlib only, so
# it runs under the system Python (3.8) without the test container. OPEN=1 opens the page.
#
# LOCAL-ONLY. scripts/ is gitignored (local tooling, CLAUDE.md §10.1), so this target
# does not work in a fresh clone — hence the guard rather than a confusing traceback.
# Two of its doc inputs (docs/status/fe-verdicts.md, docs/todo.md) are untracked too.
status:        ## regenerate the status dashboard (local only; needs scripts/status.py)
	@test -f scripts/status.py || { \
	  echo "make status: scripts/status.py is absent."; \
	  echo "  It is local-only tooling and is gitignored, so it does not ship with a clone."; \
	  exit 1; }
	python3 scripts/status.py
	@if [ -n "$(OPEN)" ]; then open docs/status/dashboard.html; fi
