.PHONY: up down logs ps build seed seed-gen psql test test-docker test-migrations migrate frontend-dev config eval

# Scoped gateway->ai-assistant secret file. Compose refuses to parse when a
# listed env_file is missing, so every compose target depends on this. The
# template ships the secret EMPTY on purpose: AI calls fail closed (503) until
# a real value is generated (see .env.ai-proxy.example).
.env.ai-proxy:
	cp .env.ai-proxy.example .env.ai-proxy

# Redis auth (docs/debt-log.md D3b), scoped to redis + gateway like the file
# above and listed as an env_file, so every compose target depends on it too.
# Unlike .env.ai-proxy this one is GENERATED rather than copied: an empty
# password makes the redis container refuse to start (fail-closed), and a
# template value would be a credential every checkout shares. One random
# password per machine, never committed.
.env.redis:
	@pw="$$(openssl rand -hex 32)"; \
	 [ -n "$$pw" ] || { echo "openssl rand failed — refusing to write an empty REDIS_PASSWORD" >&2; exit 1; }; \
	 printf '# Generated by `make` — scoped to redis + gateway (docs/debt-log.md D3b).\n# Rotate: delete this file, `make down && make up`; existing sessions are dropped.\nREDIS_PASSWORD=%s\n' "$$pw" > $@
	@echo "generated .env.redis with a random REDIS_PASSWORD"

# Registration content-binding key (e5b), scoped to intake-service and listed as
# an env_file loaded AFTER .env, like the two above. GENERATED, never templated:
# intake fails closed (503) on a missing or unreal key (e5b-SPEC-22), and a
# template value would be a shared secret AND would pass no key-real check. One
# random key per machine, never committed. Rotating it invalidates recorded
# fingerprints — bounded and visible (docs/runbook.md); a straddling retry 409s.
.env.registration:
	@key="$$(openssl rand -hex 32)"; \
	 [ -n "$$key" ] || { echo "openssl rand failed — refusing to write an empty REGISTRATION_FINGERPRINT_KEY" >&2; exit 1; }; \
	 printf '# Generated by `make` — scoped to intake-service (e5b, docs/debt-log.md).\n# Rotate: delete this file, `make down && make up`; recorded fingerprints are invalidated.\nREGISTRATION_FINGERPRINT_KEY=%s\n' "$$key" > $@
	@echo "generated .env.registration with a random REGISTRATION_FINGERPRINT_KEY"

up: .env.ai-proxy .env.redis .env.registration   ## start the whole stack
	docker compose up -d

down: .env.ai-proxy .env.redis .env.registration ## stop the stack
	docker compose down

logs: .env.ai-proxy .env.redis .env.registration ## tail logs
	docker compose logs -f

ps: .env.ai-proxy .env.redis .env.registration   ## service status
	docker compose ps

build: .env.ai-proxy .env.redis .env.registration ## build all images
	docker compose build

seed: .env.ai-proxy .env.redis .env.registration ## load schema + demo data (fresh empty db only — a re-run doubles the seed, see runbook)
	docker compose exec -T postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend} < db/schema.sql
	docker compose exec -T postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend} < db/seed/seed.sql

# Written through a temp file, not redirected onto the target: since the
# generator started reading the fixture CSVs it has failure paths (missing
# file, changed row order), and a plain `> db/seed/seed.sql` truncates the
# target BEFORE the generator runs — leaving an empty seed.sql, which
# docker-compose.yml mounts into a fresh volume's initdb without complaint.
seed-gen:      ## regenerate db/seed/seed.sql from the generator (deterministic)
	python3 db/seed/generate_seed.py > db/seed/seed.sql.tmp \
	  && mv db/seed/seed.sql.tmp db/seed/seed.sql \
	  || (rm -f db/seed/seed.sql.tmp; false)

# eval/rag/REPORT.md is a committed deliverable derived from db/seed/patients.csv,
# encounters.csv and goldset.json, and nothing noticed when the seed moved and the
# report went stale (tests/test_rag_eval.py asserts substrings, not bytes). This
# regenerates with the STUB retriever — torch-free and stdlib-only, so it runs under
# the system Python (3.8) like seed-gen and status, needs no container, no database
# and no network — and diffs against the committed file.
#
# §4's model-dependent cells are masked out of the diff: the committed report is
# embed-path output and its scores are not reproducible without the model. What is
# masked, what is deliberately NOT (the retriever label, each row's goldset-derived
# cells), and the blind spots that remain are owned by the header of
# eval/rag/check_drift.py — do not restate them here (§10.1). The mask and its red
# paths are pinned by tests/test_drift_check.py.
eval:          ## check eval/rag/REPORT.md + db/seed/seed.sql are current against their sources
	python3 eval/rag/check_drift.py

psql: .env.ai-proxy .env.redis .env.registration ## open a psql shell
	docker compose exec postgres psql -U $${DB_USER:-riverbend_app} -d $${DB_NAME:-riverbend}

test:          ## run unit tests (no infra needed)
	pip install -r requirements-dev.txt >/dev/null
	pytest -m "not integration" -q

# Same suite as `test`, but in the 3.12 container CI uses — the only way to run it
# on a machine whose local Python is 3.8. The build is a no-op (~0.6s) unless
# requirements-dev.txt changed. Pass extra pytest args via ARGS, e.g.
#   make test-docker ARGS="tests/test_redaction.py -q"
test-docker:   ## run unit tests in the python:3.12 container (mirrors CI)
	docker build -q -t riverbend-test:py312 -f Dockerfile.test . >/dev/null
	docker run --rm -v "$$PWD":/repo -w /repo riverbend-test:py312 \
	  pytest $(if $(ARGS),$(ARGS),-m "not integration" -q)

# There is no JS gate. `test-frontend` ran svelte-check, eslint and Vitest over
# the SvelteKit rebuild, which is descoped (branch alt/sveltekit-portal), and
# nothing equivalent exists for the inherited Next.js app: CI builds it and that
# is all. Adding one is real work, not a target rename.
frontend-dev:  ## run the Next.js dev server (port 3070)
	cd frontend && npm install && npm run dev

config: .env.ai-proxy .env.redis .env.registration ## validate the compose file
	docker compose config -q && echo "compose OK"

# Bring an EXISTING database up to the current schema by applying
# db/migrations/*.sql in order (e6, E6-REQ-9). Runs the one-shot `migrate`
# compose service (tools profile, no published ports). A fresh `make up` volume
# is born pre-stamped from db/schema.sql, so this reports "nothing to apply"
# there; it earns its keep on a volume created before a migration. For a legacy
# volume with no ledger, record its already-applied migrations first with
# `make migrate ARGS=baseline` (see docs/runbook.md — baseline verifies the
# volume is at head before stamping and refuses otherwise).
migrate: .env.ai-proxy .env.redis .env.registration ## apply pending migrations to the running db (ARGS=baseline for a legacy volume)
	docker compose run --rm migrate $(ARGS)

# Migration-runner integration tests against an ephemeral postgres:15 — the
# local mirror of CI's `migrations` job (the default `tests`/`test-docker` run
# deselects @pytest.mark.integration and has no Postgres). Spins a throwaway
# server, runs the two integration files in the py312 test image on a shared
# network, and tears the server down.
test-migrations: ## run the migration-runner integration tests against an ephemeral postgres:15
	@set -e; \
	 net="rb-mig-net-$$$$"; pg="rb-mig-pg-$$$$"; \
	 docker network create $$net >/dev/null; \
	 trap 'docker rm -f $$pg >/dev/null 2>&1; docker network rm $$net >/dev/null 2>&1' EXIT; \
	 docker run -d --rm --name $$pg --network $$net \
	   -e POSTGRES_DB=riverbend -e POSTGRES_USER=riverbend_app -e POSTGRES_PASSWORD=testpw \
	   postgres:15 >/dev/null; \
	 for i in $$(seq 1 30); do \
	   docker exec $$pg pg_isready -U riverbend_app -d riverbend >/dev/null 2>&1 && break; sleep 1; done; \
	 docker build -q -t riverbend-test:py312 -f Dockerfile.test . >/dev/null; \
	 docker run --rm --network $$net \
	   -e DB_HOST=$$pg -e DB_PORT=5432 -e DB_USER=riverbend_app -e DB_PASSWORD=testpw -e DB_NAME=riverbend \
	   -v "$$PWD":/repo -w /repo riverbend-test:py312 \
	   pytest -m integration tests/integration/test_migration_runner.py tests/integration/test_schema_upgrade_path.py -q

# `make status` is retired. It rendered docs/status/dashboard.html, and most of
# what it rendered was the frontend rebuild's requirement and gate track, which
# is descoped (branch alt/sveltekit-portal). What would have survived is a view
# over docs/todo.md and docs/debt-log.md — two files that are already short
# enough to read directly, and that no longer disagree with a generated copy.
# Engagement status now comes from the specs, the debt log and `gh pr list`.
